version: '3.8'

services:
  api-node:
    build: ./api-node
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - JWT_SECRET=supersecret123

  api-go:
    build: ./api-go
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - JWT_SECRET=supersecret123

  frontend:
    build: ./frontend
    ports:
      - '8080:80'

